services:
  flask-app:
    build:
      context: ./src
      dockerfile: Dockerfile.app
    container_name: flask-app-container
    ports:
      - "8096:8095"
    depends_on:
      - memcached
    environment:
      - FLASK_ENV=development
      - OPERATING_SYSTEM=docker-compose
      - MEMCACHED_HOST=memcached
    networks:
      - my_network
    links:
      - memcached
  #    volumes:
  #      - ./src:/app  Mount current directory for development
  #     /app is the working directory inside the container.
  #     ./src folder contains your code locally.
  #     You can easily debug with this, make changes on the fly why the container is running

  memcached:
    image: memcached:latest
    container_name: memcached-container
    ports:
      - "11211:11211"
    networks:
      - my_network

  test-app:
    build:
      context: ./src
      dockerfile: Dockerfile.test
    container_name: flask-tests-container
    depends_on:
      - flask-app
    networks:
      - my_network
    links:
      - flask-app
    volumes:
      - app_volume:/app
    environment:
      - TEST_TAG=${TEST_TAG:-""}
    entrypoint: ["pytest", "-m", "${TEST_TAG}", "--maxfail=5", "--disable-warnings", "--junitxml=report.xml", "--html=report.html", "--self-contained-html"]


networks:
  my_network:
    driver: bridge

volumes:
  app_volume:
    external: true