
#!/usr/bin/env -S ansible-playbook -K
# NOTE: Don't provide the playbook filename in the shebang. It is added automatically.
---

- name: Create Users playbook
  hosts: master
  remote_user: ubuntu
  become: yes
  become_user: root
  gather_facts: true

  tasks:

    ##################################
    # Update packages
    ##################################
    - name: Update apt package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    ##################################
    # Create kube_user
    ##################################
    - name: create the kube_user account
      user: name=kube_user append=yes state=present createhome=yes shell=/bin/bash

    ##################################
    # Add kube_user to sudo
    ##################################
    - name: allow 'kube_user' to use sudo without needing a password
      lineinfile:
        dest: /etc/sudoers
        line: 'kube_user ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    ##################################
    # Add kube_user pub key
    ##################################
    - name: Set up authorized keys for the kube_user
      authorized_key:
        user: kube_user
        state: present
        key: "{{ item }}"
      with_file:
        - ~/.ssh/id_kube_user_key.pub

    ##################################
    # Ensure docker group exists
    ##################################
    - name: Create docker group if it does not exist
      group:
        name: docker
        state: present

    ##################################
    # Add kube_user to docker group
    ##################################
    - name: Add 'kube_user' to the docker group
      user:
        name: kube_user
        groups: docker
        append: yes