apiVersion: v1
kind: Service
metadata:
  name: nfs-service
  namespace: storage
spec:
  ports:
  - name: nfs
    port: 2049
  - name: mountd
    port: 20048
  - name: rpcbind
    port: 111
  selector:
    app: nfs-server # must match with the label of NFS pod

# As we have deployed the NFS server using a Deployment, the server IP address can change in case of pod 
# restart. So, we need a stable DNS/IP address so that our apps can consume the volume using it. 
# So, we are going to create a Service for NFS server pods.
# Now, we can access the NFS server using nfs-service.storage.svc.cluster.local domain name.