apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  namespace: stage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: nfs-data

# You can also use the NFS volume through a PersistentVolumeClaim. You have to create a PersistentVolume 
# that will hold the information about NFS server. Then, you have to create a PersistentVolumeClaim that 
# will be bounded with the PersistentVolume. Finally, you can mount the PVC into a pod.